portfolioapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.home, name = 'home')
]

portfolioproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('portfolioapp.urls')),
]

portfolioapp/models.py
from django.db import models
from cloudinary.models import CloudinaryField

class Project(models.Model):
    name = models.CharField(max_length = 30)
    screenshot = CloudinaryField('Project screenshot')
    languages = models.TextField()
    short_description = models.TextField(default="short description")
    long_description = models.TextField(default="long description")
    link = models.URLField()
    post_date = models.DateTimeField(auto_now_add=True, null = True)

    def __str__(self):
        return self.name

    def save_project(self):
        self.save()

    def delete_project(self):
        self.delete()

    class Meta:
        ordering = ['-post_date']
    

portfolioapp/forms.py
from django import forms

class ContactForm(forms.Form):
    sender_name = forms.CharField(required=True, label = "Your name")
    sender_email = forms.EmailField(required=True, label = "Your email address")
    message = forms.CharField(widget=forms.Textarea, required=True, label = "Your message")

portfolioapp/views.py
from django.shortcuts import render
from django.conf import settings
from .models import Project
from django.core.paginator import Paginator
from django.core.mail import send_mail, EmailMessage
from .forms import ContactForm
from django.contrib import messages
from .email import send_email
from django.http import JsonResponse
from django.template.loader import render_to_string

def home(request):
    projects = Project.objects.all()
    paginator = Paginator(projects, per_page=6)
    page_number = request.GET.get('page', 1)
    page_object = paginator.get_page(page_number)
    form = ContactForm()
    if request.is_ajax():
        form = ContactForm(request.POST)
        if form.is_valid():
            sender_name = request.POST.get('sender_name')
            sender_email = request.POST.get('sender_email')
            message = request.POST.get('message')
            name = sender_name.title()
            email_name = sender_name.upper()
            send_email(email_name, message, send_email)
            data = {'Success': f'Dear {name}, thank you for your message. Your email has been sent successfully! I shall get back to you shortly.'}

            email_template = render_to_string('email/confirmation.html', {'name': name})
            email = EmailMessage(
                'Thank you for contacting Wanjiru Kamau',
                email_template,
                settings.EMAIL_HOST_USER,
                [sender_email],        
            )
            email.fail_silently = False
            email.send()
            return JsonResponse(data)

    return render(request, 'home.html', {"projects": page_object, "paginator": paginator, "page_number": int(page_number), "ContactForm": form})

portfolioapp/templates/base.html
{% load bootstrap3 %}
{% load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  {% if title %}
  <title>{{title}}</title>
  {% else %}
  <title>Wanjiru Kamau</title>
  {% endif %}

  {% block styles %}
  {% bootstrap_css %}
  <link rel="shortcut icon" href="{% static 'favicon.ico'%}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% endblock %}
</head>

<body>
  {% include "navbar.html" %}
  {% block content %}
  {%endblock%}

  {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  <script src=" {% static 'js/base.js' %}"></script>
  {% endblock %}
</body>

</html>

portfolioapp/templates/home.html
{%extends 'base.html'%}
{% load bootstrap3 %}
{% load static %}
{% block styles %}
{{ block.super}}
<link rel="stylesheet" href="{% static 'css/home.css' %}">

{% endblock %}
{% block content %}
<header class="header">
    <div class="header-content">
        <div class="box">
            <div class="title">
                <span class="block"></span>
                <h1>Wanjiru Kamau<span></span></h1>
            </div>
            <div class="role">
                <div class="block"></div>
                <p>FULL STACK DEVELOPER</p>
            </div>
        </div>
    </div>
</header>

<div id="about">
    <h1 class="text-center"><span class="underline">ABOUT</span></h1>
    <section class="d-flex about-section">
        <div class="d-flex column1 text-center">
            <img src="../../static/images/lorna.jpg" alt="lorna" class="my-image">
            <div class="about text-center">
                Hello, my name is Wanjiru Kamau. I am a Full Stack Developer with 6 months of experience. I am based in Nairobi, Kenya. I pride myself in
                creating applications with
                dynamic UI/UX and intuitive layouts. <br>I work with Python, Django, Flask, Javascript, Jquery and
                AngularJS to
                build
                applications. I am also keen to learn ReactJS and NodeJS frameworks.
            </div>
        </div>
    </section>
    <div id="skills">
        <div class="skills-title text-center">Skills</div>
        <div class="d-flex skills">
            <span class="badge">HTML</span>
            <span class="badge">CSS</span>
            <span class="badge">Javascript</span>
            <span class="badge">AngularJS</span>
            <span class="badge">Python</span>
            <span class="badge">Django</span>
            <span class="badge">Flask</span>
        </div>
    </div>
    <div class="promises">
        <div class="promise-item col-sm-4">
            <div class="hexagon">
                <img src="../../static/images/phonelink-white-18dp.svg" class="hexagon-icon">
                <div class="face1"></div>
                <div class="face2"></div>
            </div>
            <div class="text-center promise-heading">Responsive</div>
            <div class="text-center">Layouts work on any device</div>
        </div>
        <div class="promise-item col-sm-4">
            <div class="hexagon">
                <img src="../../static/images/speed-white-18dp.svg" class="hexagon-icon">
                <div class="face1"></div>
                <div class="face2"></div>
            </div>
            <div class="text-center promise-heading">Fast</div>
            <div class="text-center">Fast load times and lag free interaction</div>
        </div>
        <div class="promise-item col-sm-4">
            <div class="hexagon">
                <img src="../../static/images/emoji_objects-white-18dp.svg" class="hexagon-icon">
                <div class="face1"></div>
                <div class="face2"></div>
            </div>
            <div class="text-center promise-heading">Intuitive</div>
            <div class="text-center">Easy to use UI/UX</div>
        </div>
    </div>
</div>

<div id="projects">
    <h1 class="text-center"><span class="underline">PROJECTS</span></h1>
    <h4 class="text-center">Here are some projects I have completed</h4>
    <div class="projects">
        {% for project in projects %}
        <div class="project">
            <div class="view overlay">
                <img src="{{project.screenshot.url}}" class="img-fluid " alt="Project Screenshot">
                <div class="name">
                    <div class="mask flex-center rgba-black-strong">
                        <p class="white-text"><a href="{{project.link}}">{{project.name}}</a><br>
                            <span>{{project.languages}}</span><br><button data-toggle="modal"
                                data-target="#Project{{project.id}}" class="btn">learn more</button></p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <!-- <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li> -->
                {% for i in paginator.page_range %}
                <li class="page-item {% if i == page_number %} active {% endif %}"><a class="page-link"
                        href="?page={{i}}#projects">{{i}}</a></li>
                {% endfor %}
                <!-- <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li> -->
            </ul>
        </nav>
    </div>
</div>

<div id="contact">
    <div class="contact">
        <svg preserveAspectRatio="none" viewBox="0 0 100 102" height="75" width="100%" version="1.1"
            xmlns="http://www.w3.org/2000/svg" class="svgcolor-light">
            <path d="M0 0 L50 100 L100 0 Z" fill="white" stroke="white"></path>
        </svg>
        <h1 class="contact-title text-center"><span class="underline">CONTACT</span></h1>
        <div class="row">
            <div class="col-md-6 contact-me">
                <div class=" contact-info ">
                    <div class="bio-data"><i class="fas fa-envelope-open-text"></i>&nbsp;&nbsp;&nbsp;<span>Email :</span> lornadeveloper@gmail.com</div>
                    <div class="bio-data"><i class="fas fa-map-marker-alt"></i>&nbsp;&nbsp;&nbsp;<span>Location :</span> Nairobi, Kenya</div>
                    <div class="bio-data"><i class="fas fa-phone-square-alt"></i>&nbsp;&nbsp;&nbsp;<span>Phone :</span> + 254 706 814458</div>
                    <div class="bio-data"><i class="fab fa-github"></i>&nbsp;&nbsp;&nbsp;<span>Github :</span><a href="https://github.com/lornakamau"> lornakamau</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="second-text text-center">Have a question or want to work together?</div>
                <form method="post" id="sendEmail">
                    {% csrf_token %}
                    {% bootstrap_form ContactForm %}
                    <br>
                    <input type="submit" class="submit button" value="Send Message">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="footer">
    <div class="social-container">
        <ul class="social-icons">
            <li><a href="https://instagram.com/ciru_kamau?igshid=18joqh802fe73"><i class="fab fa-instagram"></i></a>
            </li>
            <li><a href="https://twitter.com/ciru_kamau"><i class="fab fa-twitter"></i></a></li>
            <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
            <li><a href="https://www.facebook.com/lorna.dieonne"><i class="fab fa-facebook-f"></i></a></li>
        </ul>
    </div>
</div>
<div class="copyright text-center">© Copyright Wanjiru Kamau<br>All Rights Reserved</div>

<!-- Modal -->
{% for project in projects %}
<div class="modal fade" id="Project{{project.id}}" tabindex="-1" role="dialog" aria-labelledby="projectModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img src="{{project.screenshot.url}}" class="img-fluid " alt="Project Yellow">
            </div>
            <div class="modal-footer">
                <h5 class="modal-title" id="projectModalLabel">{{project.name}}</h5>
                <div class="short-desc text-muted">{{project.short_description}}</div>
                <div class="long-desc">{{project.long_description}}</div>
                <a href="{{project.link}}" target="_blank"><button type="button" class="btn btn-primary">View site</button></a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

{% block scripts %} 
{{block.super}}
  <!-- <script type="text/javascript" src="{%static 'js/base.js'%}"></script> -->
  <script>
      const form = document.getElementById('sendEmail');
      form.addEventListener("submit", submitHandler);

      function submitHandler(event){
          event.preventDefault();
          $.ajax({
            'url':'{% url "home" %}',
            'type':'POST',
            'data':$("#sendEmail").serialize(),
            'dataType':'json',
            'success': function(data){
            alert(data['Success'])
        },
      })
      $('#id_sender_name').val('')
      $('#id_sender_email').val('')
      $("#id_message").val('')
    }


  </script>
{% endblock %}

portfolioapp/templates/navbar.html
<div class="navbar" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> WanjiruKamau </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/" class="nav-link">Home</a></li>
                <li><a href="#about" class="nav-link">About me</a></li>
                <li><a href="#projects" class="nav-link">Projects</a></li>
                <li><a href="#contact" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</div>